---
# tasks file for sample-role
- name: "Test debug task"
  debug:
    msg: "System {{ inventory_hostname }} has uuid {{ ansible_product_uuid }}"
- name: "Current folder"
  shell: "pwd"
  register: myfolder
- name: "What is my folder"
  debug:
    msg: "{{ myfolder }}"
